/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 modelh.glb
Author: T-Art (https://sketchfab.com/person-x)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/skull-face-58f4779ccfcf4cbc8b0131f89976353d
Title: Skull face
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'



useGLTF.preload('/modelh.glb')
